@startuml Exploration
actor CommandLine
participant Main
participant MazeFunctions
participant MazeSolver

CommandLine -> Main
alt commandLine prompts 
Main -> MazeFunctions: Benchmark()
else
Main -> MazeFunctions: PathChecker()
else
Main -> MazeFunctions: PathFinder()
end
MazeFunctions -> Main
Main -> MazeFunctions: Impliment()
alt
MazeFunctions -> MazeSolver: RightHandSolver()
else
MazeFunctions -> MazeSolver: TremauxSolver()
else
MazeFunctions -> MazeSolver: BFSSolver()
end
MazeSolver -> MazeFunctions
MazeFunctions -> MazeSolver: solve(maze: Maze)
MazeSolver -> MazeFunctions: return Path
MazeFunctions -> Main
Main -> CommandLine


@enduml