@startuml Exploration
actor User
participant Main
participant MazeFunctions
participant MazeSolver

User -> Main:CommandLine
alt commandLine prompts 
Main -> MazeFunctions: Benchmark(method: String, baseline: String, maze: Maze)
else
Main -> MazeFunctions: PathChecker(path: String, maze: Maze)
else
Main -> MazeFunctions: PathFinder(method: String, maze: Maze)
end
MazeFunctions -> Main
Main -> MazeFunctions: Impliment()
alt Algorithms
MazeFunctions -> MazeSolver: RightHandSolver()
else
MazeFunctions -> MazeSolver: TremauxSolver()
else
MazeFunctions -> MazeSolver: BFSSolver()
end
MazeSolver -> MazeFunctions
MazeFunctions -> MazeSolver: solve(maze: Maze)
MazeSolver -> MazeFunctions: return Path
note bottom
Print the Path
end note
MazeFunctions -> Main
Main -> User


@enduml